apiVersion: apps/v1
kind: Deployment
metadata:
  name: candles
  namespace: kafka
  labels:
    app: candles
spec:
  replicas: 2
  selector:
    matchLabels:
      app: candles
  template:
    metadata:
      labels:
        app: candles
    spec:
      containers:
      - name: candles
        image: ghcr.io/silsgah/candles:dev.0.1.5-beta.1744889947
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_INPUT_TOPIC
          value: "trades"
        - name: KAFKA_OUTPUT_TOPIC
          value: "candles"
        - name: KAFKA_CONSUMER_GROUP
          value: "candles_consumer_group"
        - name: CANDLE_SECONDS
          value: "60"