---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades
  namespace: rwml
  labels:
    app: trades
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades
  template:
    metadata:
      labels:
        app: trades
    spec:
      containers:
      - name: trades
        image: ghcr.io/silsgah/trades:dev.0.1.5-beta.
        imagePullPolicy: Always
        #
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-c6c8-kafka-bootstrap.strimzi.svc.cluster.local:9092
        - name: KAFKA_TOPIC
          value: "trades"
        - name: DATA_SOURCE
          value: "live"
        #
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi