---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backfill-technical-indicators
  namespace: rwml
data:
  KAFKA_BROKER_ADDRESS: "kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092"
  TRADES_TOPIC: "trades_historical_3f5"
  CANDLES_TOPIC: "candles_historical_3f5"
  TECHNICAL_INDICATORS_TOPIC: "technical_indicators"
  LAST_N_DAYS: "60"
  CANDLE_SECONDS: "60"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades-historical
  namespace: rwml
  labels:
    app: trades-historical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades-historical
  template:
    metadata:
      labels:
        app: trades-historical
    spec:
      containers:
      - name: trades-historical
        image: trades:dev
        imagePullPolicy: Never
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: KAFKA_BROKER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: KAFKA_BROKER_ADDRESS
        - name: KAFKA_INPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: CANDLES_TOPIC
        - name: KAFKA_OUTPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: TECHNICAL_INDICATORS_TOPIC
        - name: KAFKA_TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: TRADES_TOPIC
        - name: KAFKA_TOPIC
          value: "trades_historical"
        - name: LIVE_OR_HISTORICAL
          value: "historical"
        - name: LAST_N_DAYS
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: LAST_N_DAYS

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: candles-historical
  namespace: rwml
  labels:
    app: candles-historical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candles-historical
  template:
    metadata:
      labels:
        app: candles-historical
    spec:
      containers:
      - name: candles-historical
        image: candles:dev
        imagePullPolicy: Never
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_INPUT_TOPIC
          value: "trades_historical"
        - name: KAFKA_OUTPUT_TOPIC
          value: "candles_historical"
        - name: KAFKA_CONSUMER_GROUP
          value: "candles_consumer_group"
        - name: CANDLE_SECONDS
          value: "60"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: technical-indicators-historical
  namespace: rwml
  labels:
    app: technical-indicators-historical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: technical-indicators-historical
  template:
    metadata:
      labels:
        app: technical-indicators-historical
    spec:
      containers:
      - name: technical-indicators-historical
        image: technical-indicators:dev
        imagePullPolicy: Never
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_INPUT_TOPIC
          value: "candles_historical"
        - name: KAFKA_OUTPUT_TOPIC
          value: "technical_indicators"
        - name: KAFKA_CONSUMER_GROUP
          value: "technical_indicators_group"
        - name: CANDLE_SECONDS
          value: "60"
