---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backfill-technical-indicators
  namespace: rwml
data:
  # Quote them!!! - by Marius
  # https://12factor.net/config
  KAFKA_BROKER_ADDRESS: "kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092"
  TRADES_TOPIC: "trades_historical_3f5"
  CANDLES_TOPIC: "candles_historical_3f5"
  TECHNICAL_INDICATORS_TOPIC: "technical_indicators"
  LAST_N_DAYS: "60"
  CANDLE_SECONDS: "60"
