---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candles-historical
  namespace: rwml
  labels:
    app: candles-historical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candles-historical
  template:
    metadata:
      labels:
        app: candles-historical
    spec:
      containers:
      - name: candles-historical
        image: candles:dev
        imagePullPolicy: Never # Use the local image
        env:
        - name: KAFKA_BROKER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: KAFKA_BROKER_ADDRESS
        - name: KAFKA_INPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: TRADES_TOPIC
        - name: KAFKA_OUTPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: CANDLES_TOPIC
        - name: KAFKA_CONSUMER_GROUP
          value: "candles_consumer_group"
        - name: CANDLE_SECONDS
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: CANDLE_SECONDS
