---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prediction-api
  namespace: rwml
data:
  # Quote them!!! - by Marius
  # https://12factor.net/config
  API_PORT: "8080"
  PG_HOST: "risingwave.risingwave.svc.cluster.local"
  PG_PORT: "4567"
  PG_DATABASE: "dev"
  PG_USER: "root"
  PG_PASSWORD: ""
  PG_VIEW_NAME: "latest_predictions"
  RUST_LOG: "info"